version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: silentsanta-postgres
    restart: always
    environment:
      POSTGRES_DB: silentsanta
      POSTGRES_USER: silentsanta
      POSTGRES_PASSWORD: strongpass123
    ports:
      - "5432:5432"
    volumes:
      - wishlist_pgdata:/var/lib/postgresql/data

volumes:
  wishlist_pgdata:
